name: Maven Releasing

on:

  release:
    types: [created]

jobs:
  release:
    permissions:
      contents: write # may want to update version
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_SETTINGS_EXPERIM: ${{ vars.MAVEN_SETTINGS_FILE }}
      GPG_PASSPHRASE_PRELIM: ${{ secrets.GPG_PASSPHRASE }}
      RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      IS_PRERELEASE: ${{ github.event.release.prerelease }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Add dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
      - name: Check environment
        run: |
          # TODO this is a debug step and can be removed before push to production
          env
      - name: Verify
        run: |
          if [[ -n "$SONATYPE_USERNAME" ]]
          then
            echo "DEBUG have SONATYPE_USERNAME"
          else
            echo "Release requires SONATYPE_USERNAME, which was not found. exiting"
            exit 1
          fi

          if [[ -n "$SONATYPE_PASSWORD" ]]
          then
            echo "have SONATYPE_PASSWORD"
          else
            echo "Release requires SONATYPE_PASSWORD, which was not found. exiting"
            exit 1
          fi

          if [[ -n "$GPG_PASSPHRASE_PRELIM" ]]
          then
            echo "have GPG_PASSPHRASE_PRELIM"
          else
            echo "Release requires GPG_PASSPHRASE, which was not found. exiting"
            exit 1
          fi

          if [[ "$GPG_PASSPHRASE_PRELIM" == "EMPTY" ]]
          then
            echo "GPG_PASSPHRASE empty requested"
            export GPG_PASSPHRASE=""
          else
            export GPG_PASSPHRASE="$GPG_PASSPHRASE_PRELIM"
          fi

          echo "DEBUG GPG_PASSPHRASE ${GPG_PASSPHRASE}"

          echo "GPG_PASSPHRASE=${GPG_PASSPHRASE}" >> $GITHUB_ENV

          echo "ROVER_ACTION=JUMP_THE_FENCE" >> $GITHUB_ENV

          # Verify GPG2 environment
          if ! command -v gpg2 &> /dev/null
          then
            echo "Failed to locate gpg2 on this host.  GPG2 is required to continue."
            exit 1
          fi

          gpg2 --version
          export GPG_EXECUTABLE=$(command -v gpg2)
          echo "DEBUG GPG_EXECUTABLE ${GPG_EXECUTABLE}"

          echo "DEBUG MAVEN_SETTINGS_EXPERIM ${MAVEN_SETTINGS_EXPERIM}"
          echo "DEBUG MAVEN_SETTINGS_FILE ${{ vars.MAVEN_SETTINGS_FILE }}"

          # N.B. this is for debugging only.  TODO remove before release
          mvn -s ${{ vars.MAVEN_SETTINGS_FILE }} help:effective-settings
          # mvn help:effective-settings
      - name: Script
        run: |
          echo "DEBUG IS_PRERELEASE ^^^${IS_PRERELEASE}^^^"
          echo "DEBUG GITHUB_ACTOR ${GITHUB_ACTOR}"
          ./scripts/on-release.sh
      - name: Model release
        run: |
          if [[ "${IS_PRERELEASE}" == "true" ]]; then
             echo "This is a pre release and will not be deployed to Maven Central."
             exit 0
          fi
          cat << EOF > release.properties
          scm.url=scm\:git\:https\://github.com/${GITHUB_REPOSITORY}.git
          scm.tag=${RELEASE_TAG_NAME}
          EOF
          cat release.properties
          ls -al
          # TODO fix -Darguments - we don't want to skip everything in production
          mvn release:perform \
            -Dgoals=deploy \
            -s ./deploy-settings.xml \
            -Darguments="-DskipTests -DskipITs -Dlicense.skip -DperformRelease=true"
      - name: Publish documentation
        run: |
          if [[ "${IS_PRERELEASE}" == "true" ]]; then
             echo "This is a pre release, so site documentation will not be updated to Github pages."
             exit 0
          fi
          mvn clean site site:stage -DskipTests
          mvn scm-publish:publish-scm
      - name: Prepare next cycle
        run: |
          # DEBUGGING config follows
          set -x
          if [[ "${IS_PRERELEASE}" == "true" ]]; then
            echo "This is a prerelease so the next release cycle will not be prepared."
            # exit 0
            echo "Continue for now for debugging and review"
          fi
          echo "Preparing next release cycle"

          VERSION_CLEAN=${RELEASE_TAG_NAME}
          PARTS=(${VERSION_CLEAN//./ })
          NEW_MINOR=$((PARTS[1]+1))
          NEXT_RELEASE="${PARTS[0]}.${NEW_MINOR}.${PARTS[2]}"
          NEXT_RELEASE_BRANCH="ci/next-cycle-${NEXT_RELEASE}"
          gh --version
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name ${GITHUB_ACTOR}
          git checkout -b ${NEXT_RELEASE_BRANCH}
          mvn versions:set-scm-tag  -DnewTag="HEAD"
          mvn versions:set -DnextSnapshot=true -DnextSnapshotIndexToIncrement=2
          sed -i "1s/^/## ${NEXT_RELEASE:1} [unreleased]\n\n/" CHANGELOG.md
          sed -i -e "s/<version>${RELEASE_TAG_NAME:1}<\/version>/<version>${NEXT_RELEASE:1}-SNAPSHOT<\/version>/" examples/pom.xml
          # DEBUG step follows
          git diff
          git add pom.xml CHANGELOG.md
          git commit -m "ci: setting up release cycle ${NEXT_RELEASE:1}"
          git push --set-upstream origin ${NEXT_RELEASE_BRANCH}
          echo "The branch ${NEXT_RELEASE_BRANCH} has been created.  You can create and merge a PR manually from it to start the next release cycle."
